### ISSUE TITLE
Replace mailhog with mailpit

### ISSUE THREAD

**Issue by d70rr3s** [hinternet/drupal-develop#20]
The [mailhog](https://github.com/mailhog/MailHog) service has a very slow cycle development and has some issues when working on ARM64. While these problems persist we will be switching to [mailpit](https://github.com/axllent/mailpit).

Required changes:
- Replace `mailhog` service definition at `scaffold/templates/docker/docker-compose.yml` with
```
  mailpit:
    image: "axllent/mailpit:${MAILPIT_TAG}"
    container_name: "${PROJECT_NAME}_mailpit"
    labels:
      - "traefik.http.services.${PROJECT_NAME}_mailpit.loadbalancer.server.port=8025"
      - "traefik.http.routers.${PROJECT_NAME}_mailpit.rule=Host(`mailpit.${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}_mailpit.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}_mailpit.tls"
    volumes:
      - mailpit:/data
```
- Rename any references from `mailhog` to `mailpit`
- Add `mailpit` volume to `volumes` section in docker-compose.yml
- Add env vars to the `scaffold/templates/docker/.env.dist` template on the **Mail settings** section.
```
# Mail settings
MAILPIT_TAG=v1.8
MAILPIT_DATA_FILE=/data/mailpit.db 
```
